FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
COPY seeder.py .
COPY entry.sh .

RUN pip install --no-cache-dir -r requirements.txt && chmod +x entry.sh

ENTRYPOINT [ "./entry.sh" ]